module.exports = {
    plugins: [
        'stylelint-order',
        'stylelint-stylistic',
    ],
    rules: {
        // нативные правила stylelint'а
        // ========================================
        'block-no-empty': true,
        'selector-max-universal': 0,
        'selector-max-id': 0,
        'max-nesting-depth': 4,
        'color-hex-length': 'short',
        'color-named': 'never',
        'color-no-hex': null,
        'color-no-invalid-hex': true,
        'font-family-name-quotes': 'always-where-recommended',
        'font-family-no-duplicate-names': true,
        'font-weight-notation': 'named-where-possible',
        'number-max-precision': 3,
        'string-no-newline': true,
        'length-zero-no-unit': true,
        'time-min-milliseconds': 100,
        'unit-disallowed-list': [],
        'unit-no-unknown': true,
        'value-keyword-case': ['lower', { ignoreProperties: '/font/', camelCaseSvgKeywords: true }],
        'value-no-vendor-prefix': null,
        'function-disallowed-list': [],
        'function-calc-no-unspaced-operator': true,
        'function-linear-gradient-no-nonstandard-direction': true,
        'function-name-case': 'lower',
        'function-url-quotes': 'always',
        'function-url-scheme-allowed-list': ['https', 'data'],
        'selector-pseudo-element-colon-notation': 'double',
        'selector-pseudo-element-no-unknown': true,
        'selector-type-case': 'lower',
        'selector-type-no-unknown': [true, { ignoreTypes: ['/^[$]/'] }],
        'selector-pseudo-class-no-unknown': [
            true,
            {
                ignorePseudoClasses: ['global'],
            },
        ],
        'shorthand-property-no-redundant-values': true,
        'property-disallowed-list': [],
        'property-no-unknown': true,
        'property-no-vendor-prefix': null,
        'keyframe-declaration-no-important': true,
        'declaration-property-unit-disallowed-list': {},
        'declaration-property-value-disallowed-list': {},
        'declaration-block-no-duplicate-properties': [true, { ignore: ['consecutive-duplicates'] }],
        'declaration-block-no-redundant-longhand-properties': [true, { ignoreShorthands: ['/flex-/', 'inset'] }],
        'declaration-block-no-shorthand-property-overrides': true,
        'declaration-block-single-line-max-declarations': 1,
        'at-rule-empty-line-before': [
            'always',
            {
                except: ['first-nested', 'blockless-after-same-name-blockless'],
                ignore: ['after-comment'],
            },
        ],
        'at-rule-no-unknown': [
            true,
            {
                ignoreAtRules: ['for', 'mixin', 'define-mixin', 'media', 'mixin-content', 'each', 'include'],
            },
        ],
        'rule-empty-line-before': [
            'always',
            {
                except: ['first-nested'],
                ignore: ['after-comment', 'first-nested'],
            },
        ],
        'comment-no-empty': true,
        'comment-whitespace-inside': 'always',
        'no-descending-specificity': true,
        'no-duplicate-selectors': true,
        'no-empty-source': true,
        'no-invalid-double-slash-comments': true,
        'no-unknown-animations': true,

        // правила из stylelint-order
        // ========================================
        'order/order': [
            { type: 'at-rule', name: 'import' },
            'dollar-variables',
            'custom-properties',
            'declarations',
            { type: 'at-rule' },
            { type: 'at-rule', hasBlock: true },
            'rules',
        ],
        'order/properties-order': [
            {
                emptyLineBefore: 'always',
                noEmptyLineBetween: true,
                properties: ['position', 'z-index', 'top', 'right', 'bottom', 'left', 'inset'],
            },
            {
                emptyLineBefore: 'always',
                noEmptyLineBetween: true,
                properties: [
                    'display',
                    'box-orient',
                    'line-clamp',
                    'visibility',
                    'float',
                    'clear',
                    'overflow',
                    'overflow-x',
                    'overflow-y',
                    'overflow-scrolling',
                    'clip',
                    'zoom',
                    'flex',
                    'flex-grow',
                    'flex-direction',
                    'flex-order',
                    'flex-pack',
                    'flex-align',
                    'flex-flow',
                    'flex-basis',
                    'flex-shrink',
                    'flex-wrap',
                    'justify-content',
                    'align-content',
                    'align-items',
                    'align-self',
                    'order',
                    'grid',
                    'grid-area',
                    'grid-template',
                    'grid-template-areas',
                    'grid-template-columns',
                    'grid-template-rows',
                    'grid-auto-columns',
                    'grid-auto-flow',
                    'grid-auto-rows',
                    'grid-column',
                    'grid-column-end',
                    'grid-column-start',
                    'grid-row',
                    'grid-row-end',
                    'grid-row-start',
                ],
            },
            {
                emptyLineBefore: 'always',
                noEmptyLineBetween: true,
                properties: [
                    'box-sizing',
                    'width',
                    'min-width',
                    'max-width',
                    'height',
                    'min-height',
                    'max-height',
                    'margin',
                    'margin-top',
                    'margin-right',
                    'margin-bottom',
                    'margin-left',
                    'padding',
                    'padding-top',
                    'padding-right',
                    'padding-bottom',
                    'padding-left',
                ],
            },
            {
                emptyLineBefore: 'always',
                noEmptyLineBetween: true,
                properties: [
                    'table-layout',
                    'empty-cells',
                    'caption-side',
                    'border-spacing',
                    'border-collapse',
                    'list-style',
                    'list-style-position',
                    'list-style-type',
                    'list-style-image',
                ],
            },
            {
                emptyLineBefore: 'always',
                noEmptyLineBetween: true,
                properties: [
                    'font',
                    'font-family',
                    'src',
                    'font-size',
                    'font-weight',
                    'font-style',
                    'font-variant',
                    'font-size-adjust',
                    'font-stretch',
                    'font-effect',
                    'font-emphasize',
                    'font-emphasize-position',
                    'font-emphasize-style',
                    'font-smooth',
                    'line-height',
                    'content',
                    'quotes',
                    'counter-reset',
                    'counter-increment',
                    'resize',
                    'cursor',
                    'user-select',
                    'nav-index',
                    'nav-up',
                    'nav-right',
                    'nav-down',
                    'nav-left',
                    'text-align',
                    'text-align-last',
                    'vertical-align',
                    'white-space',
                    'text-decoration',
                    'text-emphasis',
                    'text-emphasis-color',
                    'text-emphasis-style',
                    'text-emphasis-position',
                    'text-indent',
                    'text-justify',
                    'letter-spacing',
                    'word-spacing',
                    'text-outline',
                    'text-transform',
                    'text-wrap',
                    'text-orientation',
                    'text-overflow',
                    'text-overflow-ellipsis',
                    'text-overflow-mode',
                    'word-wrap',
                    'word-break',
                    'tab-size',
                    'hyphens',
                    'pointer-events',
                    'caret-color',
                    'direction',
                ],
            },
            {
                emptyLineBefore: 'always',
                noEmptyLineBetween: true,
                properties: [
                    'opacity',
                    'color',
                    'border',
                    'border-width',
                    'border-style',
                    'border-color',
                    'border-top',
                    'border-top-width',
                    'border-top-style',
                    'border-top-color',
                    'border-right',
                    'border-right-width',
                    'border-right-style',
                    'border-right-color',
                    'border-bottom',
                    'border-bottom-width',
                    'border-bottom-style',
                    'border-bottom-color',
                    'border-left',
                    'border-left-width',
                    'border-left-style',
                    'border-left-color',
                    'border-radius',
                    'border-top-left-radius',
                    'border-top-right-radius',
                    'border-bottom-right-radius',
                    'border-bottom-left-radius',
                    'border-image',
                    'border-image-source',
                    'border-image-slice',
                    'border-image-width',
                    'border-image-outset',
                    'border-image-repeat',
                    'outline',
                    'outline-width',
                    'outline-style',
                    'outline-color',
                    'outline-offset',
                    'background',
                    'background-color',
                    'background-image',
                    'background-repeat',
                    'background-attachment',
                    'background-position',
                    'background-position-x',
                    'background-position-y',
                    'background-clip',
                    'background-origin',
                    'background-size',
                    'object-fit',
                    'object-position',
                    'box-decoration-break',
                    'box-shadow',
                    'text-shadow',
                    'mask',
                    'filter',
                    'highlight-color',
                    'fill',
                ],
            },
            {
                emptyLineBefore: 'always',
                noEmptyLineBetween: true,
                properties: [
                    'transition',
                    'transition-delay',
                    'transition-timing-function',
                    'transition-duration',
                    'transition-property',
                    'transform',
                    'transform-origin',
                    'animation',
                    'animation-name',
                    'animation-duration',
                    'animation-play-state',
                    'animation-timing-function',
                    'animation-delay',
                    'animation-iteration-count',
                    'animation-direction',
                ],
            },
        ],

        // правила из stylelint-stylistic
        // ========================================
        'stylistic/property-case': 'lower',
        'stylistic/color-hex-case': 'lower',
        'stylistic/function-comma-newline-after': 'always-multi-line',
        'stylistic/function-comma-newline-before': 'never-multi-line',
        'stylistic/function-comma-space-after': 'always',
        'stylistic/function-comma-space-before': 'never',
        'stylistic/function-max-empty-lines': 0,
        'stylistic/function-parentheses-newline-inside': 'never-multi-line',
        'stylistic/function-parentheses-space-inside': 'never',
        'stylistic/function-whitespace-after': 'always',
        'stylistic/number-leading-zero': 'never',
        'stylistic/number-no-trailing-zeros': true,
        'stylistic/string-quotes': 'single',
        'stylistic/unit-case': 'lower',
        'stylistic/value-list-comma-newline-after': 'always-multi-line',
        'stylistic/value-list-comma-newline-before': 'never-multi-line',
        'stylistic/value-list-comma-space-after': 'always',
        'stylistic/value-list-comma-space-before': 'never',
        'stylistic/value-list-max-empty-lines': 0,
        'stylistic/declaration-bang-space-after': 'never',
        'stylistic/declaration-bang-space-before': 'always',
        'stylistic/declaration-colon-newline-after': 'always-multi-line',
        'stylistic/declaration-colon-space-after': 'always-single-line',
        'stylistic/declaration-colon-space-before': 'never',
        'stylistic/declaration-block-semicolon-newline-after': 'always',
        'stylistic/declaration-block-semicolon-newline-before': 'never-multi-line',
        'stylistic/declaration-block-semicolon-space-after': 'always-single-line',
        'stylistic/declaration-block-semicolon-space-before': 'never',
        'stylistic/declaration-block-trailing-semicolon': 'always',
        'stylistic/block-closing-brace-empty-line-before': 'never',
        'stylistic/block-closing-brace-newline-after': 'always',
        'stylistic/block-opening-brace-newline-after': 'always',
        'stylistic/block-closing-brace-newline-before': 'always',
        'stylistic/block-opening-brace-space-before': 'always',
        'stylistic/selector-attribute-brackets-space-inside': 'never',
        'stylistic/selector-combinator-space-after': 'always',
        'stylistic/selector-combinator-space-before': 'always',
        'stylistic/selector-pseudo-class-case': 'lower',
        'stylistic/selector-pseudo-class-parentheses-space-inside': 'never',
        'stylistic/selector-pseudo-element-case': 'lower',
        'stylistic/selector-max-empty-lines': 0,
        'stylistic/selector-list-comma-newline-after': 'always',
        'stylistic/selector-list-comma-newline-before': 'never-multi-line',
        'stylistic/selector-list-comma-space-before': 'never',
        'stylistic/media-feature-colon-space-after': 'always',
        'stylistic/media-feature-colon-space-before': 'never',
        'stylistic/media-feature-name-case': 'lower',
        'stylistic/media-feature-parentheses-space-inside': 'never',
        'stylistic/media-feature-range-operator-space-after': 'always',
        'stylistic/media-feature-range-operator-space-before': 'always',
        'stylistic/media-query-list-comma-newline-after': 'always-multi-line',
        'stylistic/media-query-list-comma-space-after': 'always-single-line',
        'stylistic/at-rule-name-case': 'lower',
        'stylistic/at-rule-name-space-after': 'always',
        'stylistic/at-rule-semicolon-newline-after': 'always',
        'stylistic/indentation': 4,
        'stylistic/linebreaks': 'unix',
        'stylistic/max-line-length': [120, { ignore: ['comments'], ignorePattern: '/gradient\\(.*\\)/' }],
        'stylistic/max-empty-lines': 1,
        'stylistic/no-eol-whitespace': true,
        'stylistic/no-extra-semicolons': true,
        'stylistic/no-missing-end-of-source-newline': true,
        'stylistic/no-empty-first-line': true,
    },
};
