export const SETTINGS_PENDING = 'SETTINGS_PENDING';
export const SETTINGS_SUCCESS = 'SETTINGS_SUCCESS';
export const SETTINGS_FAILURE = 'SETTINGS_FAILURE';

export const UPDATE_SETTINGS_PENDING = 'UPDATE_SETTINGS_PENDING';
export const UPDATE_SETTTINGS_SUCCESS = 'UPDATE_SETTTINGS_SUCCESS';
export const UPDATE_SETTINGS_FAILURE = 'UPDATE_SETTINGS_FAILURE';
