name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'blog/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [12]
    
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER: ${{ secrets.DOCKER_NAME }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: Build Frontend
      run: |
        cd blog
        npm i
        ls -la
        docker build -t kletskovg/blog:prod .
        docker run -d -p 80:80 kletskovg/blog:prod
        npm run test

  ### Second Job
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [12]
    
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER: ${{ secrets.DOCKER_NAME }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: Publish blog to registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kletskovg/blog:latest
        username: ${{secrets.DOCKER_LOGIN}}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: ./blog
    - name: Update cluster
      run: ${{ secrets.UPDATE_CLUSTER }}
