name: Build

on:
  pull_request:
    branches:
      - master
      - develop
    types:
      [opened]

jobs:
 
  # New job
  build:
    name: build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [12]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER: ${{ secrets.DOCKER_NAME }}

    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
 
  # New job
  test_front:
    name: testFront
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [12]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER: ${{ secrets.DOCKER_NAME }}
    needs: build
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: Testing frontend
      run: |
        cd client
        npm i
        docker build -t kletskovg/sitefrontend:prod .
        docker run -d -p 80:80 kletskovg/sitefrontend:prod
        npm run test
  
  test_back:
    name: test_back
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [12]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER: ${{ secrets.DOCKER_NAME }}
    needs: build
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: Testing backend
      run: |
        cd server
        npm i
        docker build -t kletskovg/sitebackend:latest .
        docker run -d -p 8080:8080 kletskovg/sitebackend:latest
        npm run test
   q