name: Common
on:
  [push]
jobs:
  Lint:
    name: Run linters in server package
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v4
      - name: Lint
        uses: actions/setup-node@v3
        with:
          node-version: '21.4.0'
      - run: cd ./server && npm i
      - run: cd ./server && npm run lint
  Typechecking:
    name: Run TS typechecks
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v4
      - name: Lint
        uses: actions/setup-node@v3
        with:
          node-version: '21.4.0'
      - run: cd ./server && npm i
      - run: cd ./server && npm run typechecking
      