name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [12]
    
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER: ${{ secrets.DOCKER_NAME }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    # - name: Build server
    #   run: |
    #     cd server
    #     yarn install
    #     yarn build
    # - name: Publish Server to Registry
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: kletskovg/sitebackend:latest
    #     username: ${{secrets.DOCKER_LOGIN}}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     context: ./server
    # - name: Pull backend image
    #   run: |
    #     curl ${{ secrets.PULL_BACKEND }}
    - name: Build Frontend
      run: |
        cd client
        npm i
        npm run ng build --prod
        npm run ng serve --prod=true & npm run test
        cd ../
    # - name: Push frontend to registry
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: kletskovg/sitefrontend:prod
    #     username: ${{secrets.DOCKER_LOGIN}}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     context: ./client
    # - name: Pull frontend image
    #   run: |
    #     curl ${{ secrets.PULL_FRONTEND }}
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [12]
    
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER: ${{ secrets.DOCKER_NAME }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: Build server
      run: |
        cd server
        yarn install
        yarn build
    - name: Publish Server to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kletskovg/sitebackend:latest
        username: ${{secrets.DOCKER_LOGIN}}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: ./server
    - name: Pull backend image
      run: |
        curl ${{ secrets.PULL_BACKEND }}
    - name: Push frontend to registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kletskovg/sitefrontend:prod
        username: ${{secrets.DOCKER_LOGIN}}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: ./client
    - name: Pull frontend image
      run: |
        curl ${{ secrets.PULL_FRONTEND }}
    