name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [12]
    
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER: ${{ secrets.DOCKER_NAME }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: Build server
      run: |
        cd server
        yarn install
        yarn build
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kletskovg/sitebackend
        username: ${{secrets.DOCKER_LOGIN}}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: ./server
    - name: test Curl
      run: |
        curl https://google.com