name: Main CI
on:
  push:
    branches:
      - master
jobs:
  Frontend:
    name: Push Sitefrontend to Docker Hub
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./client
          file: ./client/Dockerfile
          tags: kletskovg/sitefrontend:latest
          push: true
  Frontend_Notification:
    needs: Frontend
    name: Send notification Frontend
    runs-on: ubuntu-latest
    steps:
      - run: curl https://telegram.kletskovg.tech/done/frontend_published
  Backend:
    name: Push InfraServer to Docker Hub
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./server
          file: ./server/Dockerfile
          tags: kletskovg/content:latest
          push: true
  Backend_Notification:
    needs: Backend
    name: Send notification Backend
    runs-on: ubuntu-latest
    steps:
      - run: curl https://telegram.kletskovg.tech/done/Backend_published